# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExternalBufferGroup(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExternalBufferGroup()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExternalBufferGroup(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ExternalBufferGroupBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # ExternalBufferGroup
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExternalBufferGroup
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ExternalBufferGroupStart(builder):
    builder.StartObject(1)

def Start(builder):
    ExternalBufferGroupStart(builder)

def ExternalBufferGroupAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ExternalBufferGroupAddName(builder, name)

def ExternalBufferGroupEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExternalBufferGroupEnd(builder)


class ExternalBufferGroupT(object):

    # ExternalBufferGroupT
    def __init__(self):
        self.name = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        externalBufferGroup = ExternalBufferGroup()
        externalBufferGroup.Init(buf, pos)
        return cls.InitFromObj(externalBufferGroup)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, externalBufferGroup):
        x = ExternalBufferGroupT()
        x._UnPack(externalBufferGroup)
        return x

    # ExternalBufferGroupT
    def _UnPack(self, externalBufferGroup):
        if externalBufferGroup is None:
            return
        self.name = externalBufferGroup.Name()

    # ExternalBufferGroupT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        ExternalBufferGroupStart(builder)
        if self.name is not None:
            ExternalBufferGroupAddName(builder, name)
        externalBufferGroup = ExternalBufferGroupEnd(builder)
        return externalBufferGroup
