# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExternalBuffer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExternalBuffer()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExternalBuffer(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ExternalBufferBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # ExternalBuffer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExternalBuffer
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalBuffer
    def Group(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ExternalBuffer
    def Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ExternalBuffer
    def Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ExternalBuffer
    def Packing(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ExternalBufferStart(builder):
    builder.StartObject(5)

def Start(builder):
    ExternalBufferStart(builder)

def ExternalBufferAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    ExternalBufferAddId(builder, id)

def ExternalBufferAddGroup(builder, group):
    builder.PrependUint32Slot(1, group, 0)

def AddGroup(builder, group):
    ExternalBufferAddGroup(builder, group)

def ExternalBufferAddOffset(builder, offset):
    builder.PrependUint64Slot(2, offset, 0)

def AddOffset(builder, offset):
    ExternalBufferAddOffset(builder, offset)

def ExternalBufferAddLength(builder, length):
    builder.PrependUint64Slot(3, length, 0)

def AddLength(builder, length):
    ExternalBufferAddLength(builder, length)

def ExternalBufferAddPacking(builder, packing):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(packing), 0)

def AddPacking(builder, packing):
    ExternalBufferAddPacking(builder, packing)

def ExternalBufferEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExternalBufferEnd(builder)


class ExternalBufferT(object):

    # ExternalBufferT
    def __init__(self):
        self.id = 0  # type: int
        self.group = 0  # type: int
        self.offset = 0  # type: int
        self.length = 0  # type: int
        self.packing = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        externalBuffer = ExternalBuffer()
        externalBuffer.Init(buf, pos)
        return cls.InitFromObj(externalBuffer)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, externalBuffer):
        x = ExternalBufferT()
        x._UnPack(externalBuffer)
        return x

    # ExternalBufferT
    def _UnPack(self, externalBuffer):
        if externalBuffer is None:
            return
        self.id = externalBuffer.Id()
        self.group = externalBuffer.Group()
        self.offset = externalBuffer.Offset()
        self.length = externalBuffer.Length()
        self.packing = externalBuffer.Packing()

    # ExternalBufferT
    def Pack(self, builder):
        if self.packing is not None:
            packing = builder.CreateString(self.packing)
        ExternalBufferStart(builder)
        ExternalBufferAddId(builder, self.id)
        ExternalBufferAddGroup(builder, self.group)
        ExternalBufferAddOffset(builder, self.offset)
        ExternalBufferAddLength(builder, self.length)
        if self.packing is not None:
            ExternalBufferAddPacking(builder, packing)
        externalBuffer = ExternalBufferEnd(builder)
        return externalBuffer
