# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MultiAxisQuantization(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MultiAxisQuantization()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMultiAxisQuantization(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MultiAxisQuantizationBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # MultiAxisQuantization
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MultiAxisQuantization
    def Scales(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MultiAxisQuantization
    def ZeroPoints(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MultiAxisQuantization
    def BlockSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MultiAxisQuantization
    def QuantizedDimensions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # MultiAxisQuantization
    def QuantizedDimensionsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # MultiAxisQuantization
    def QuantizedDimensionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MultiAxisQuantization
    def QuantizedDimensionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def MultiAxisQuantizationStart(builder):
    builder.StartObject(4)

def Start(builder):
    MultiAxisQuantizationStart(builder)

def MultiAxisQuantizationAddScales(builder, scales):
    builder.PrependInt32Slot(0, scales, 0)

def AddScales(builder, scales):
    MultiAxisQuantizationAddScales(builder, scales)

def MultiAxisQuantizationAddZeroPoints(builder, zeroPoints):
    builder.PrependInt32Slot(1, zeroPoints, 0)

def AddZeroPoints(builder, zeroPoints):
    MultiAxisQuantizationAddZeroPoints(builder, zeroPoints)

def MultiAxisQuantizationAddBlockSize(builder, blockSize):
    builder.PrependInt32Slot(2, blockSize, 0)

def AddBlockSize(builder, blockSize):
    MultiAxisQuantizationAddBlockSize(builder, blockSize)

def MultiAxisQuantizationAddQuantizedDimensions(builder, quantizedDimensions):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(quantizedDimensions), 0)

def AddQuantizedDimensions(builder, quantizedDimensions):
    MultiAxisQuantizationAddQuantizedDimensions(builder, quantizedDimensions)

def MultiAxisQuantizationStartQuantizedDimensionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartQuantizedDimensionsVector(builder, numElems):
    return MultiAxisQuantizationStartQuantizedDimensionsVector(builder, numElems)

def MultiAxisQuantizationEnd(builder):
    return builder.EndObject()

def End(builder):
    return MultiAxisQuantizationEnd(builder)

try:
    from typing import List
except:
    pass

class MultiAxisQuantizationT(object):

    # MultiAxisQuantizationT
    def __init__(self):
        self.scales = 0  # type: int
        self.zeroPoints = 0  # type: int
        self.blockSize = 0  # type: int
        self.quantizedDimensions = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        multiAxisQuantization = MultiAxisQuantization()
        multiAxisQuantization.Init(buf, pos)
        return cls.InitFromObj(multiAxisQuantization)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, multiAxisQuantization):
        x = MultiAxisQuantizationT()
        x._UnPack(multiAxisQuantization)
        return x

    # MultiAxisQuantizationT
    def _UnPack(self, multiAxisQuantization):
        if multiAxisQuantization is None:
            return
        self.scales = multiAxisQuantization.Scales()
        self.zeroPoints = multiAxisQuantization.ZeroPoints()
        self.blockSize = multiAxisQuantization.BlockSize()
        if not multiAxisQuantization.QuantizedDimensionsIsNone():
            if np is None:
                self.quantizedDimensions = []
                for i in range(multiAxisQuantization.QuantizedDimensionsLength()):
                    self.quantizedDimensions.append(multiAxisQuantization.QuantizedDimensions(i))
            else:
                self.quantizedDimensions = multiAxisQuantization.QuantizedDimensionsAsNumpy()

    # MultiAxisQuantizationT
    def Pack(self, builder):
        if self.quantizedDimensions is not None:
            if np is not None and type(self.quantizedDimensions) is np.ndarray:
                quantizedDimensions = builder.CreateNumpyVector(self.quantizedDimensions)
            else:
                MultiAxisQuantizationStartQuantizedDimensionsVector(builder, len(self.quantizedDimensions))
                for i in reversed(range(len(self.quantizedDimensions))):
                    builder.PrependInt32(self.quantizedDimensions[i])
                quantizedDimensions = builder.EndVector()
        MultiAxisQuantizationStart(builder)
        MultiAxisQuantizationAddScales(builder, self.scales)
        MultiAxisQuantizationAddZeroPoints(builder, self.zeroPoints)
        MultiAxisQuantizationAddBlockSize(builder, self.blockSize)
        if self.quantizedDimensions is not None:
            MultiAxisQuantizationAddQuantizedDimensions(builder, quantizedDimensions)
        multiAxisQuantization = MultiAxisQuantizationEnd(builder)
        return multiAxisQuantization
