# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

class QuantizationDetails(object):
    NONE = 0
    CustomQuantization = 1
    BlockwiseQuantization = 2
    MultiAxisQuantization = 3

def QuantizationDetailsCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == QuantizationDetails.CustomQuantization:
        import tflite.CustomQuantization
        return tflite.CustomQuantization.CustomQuantizationT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == QuantizationDetails.BlockwiseQuantization:
        import tflite.BlockwiseQuantization
        return tflite.BlockwiseQuantization.BlockwiseQuantizationT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == QuantizationDetails.MultiAxisQuantization:
        import tflite.MultiAxisQuantization
        return tflite.MultiAxisQuantization.MultiAxisQuantizationT.InitFromBuf(table.Bytes, table.Pos)
    return None
