# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StablehloCaseOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StablehloCaseOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStablehloCaseOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StablehloCaseOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # StablehloCaseOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StablehloCaseOptions
    def BranchSubgraphIndices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # StablehloCaseOptions
    def BranchSubgraphIndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # StablehloCaseOptions
    def BranchSubgraphIndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StablehloCaseOptions
    def BranchSubgraphIndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def StablehloCaseOptionsStart(builder):
    builder.StartObject(1)

def Start(builder):
    StablehloCaseOptionsStart(builder)

def StablehloCaseOptionsAddBranchSubgraphIndices(builder, branchSubgraphIndices):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(branchSubgraphIndices), 0)

def AddBranchSubgraphIndices(builder, branchSubgraphIndices):
    StablehloCaseOptionsAddBranchSubgraphIndices(builder, branchSubgraphIndices)

def StablehloCaseOptionsStartBranchSubgraphIndicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBranchSubgraphIndicesVector(builder, numElems):
    return StablehloCaseOptionsStartBranchSubgraphIndicesVector(builder, numElems)

def StablehloCaseOptionsEnd(builder):
    return builder.EndObject()

def End(builder):
    return StablehloCaseOptionsEnd(builder)

try:
    from typing import List
except:
    pass

class StablehloCaseOptionsT(object):

    # StablehloCaseOptionsT
    def __init__(self):
        self.branchSubgraphIndices = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        stablehloCaseOptions = StablehloCaseOptions()
        stablehloCaseOptions.Init(buf, pos)
        return cls.InitFromObj(stablehloCaseOptions)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, stablehloCaseOptions):
        x = StablehloCaseOptionsT()
        x._UnPack(stablehloCaseOptions)
        return x

    # StablehloCaseOptionsT
    def _UnPack(self, stablehloCaseOptions):
        if stablehloCaseOptions is None:
            return
        if not stablehloCaseOptions.BranchSubgraphIndicesIsNone():
            if np is None:
                self.branchSubgraphIndices = []
                for i in range(stablehloCaseOptions.BranchSubgraphIndicesLength()):
                    self.branchSubgraphIndices.append(stablehloCaseOptions.BranchSubgraphIndices(i))
            else:
                self.branchSubgraphIndices = stablehloCaseOptions.BranchSubgraphIndicesAsNumpy()

    # StablehloCaseOptionsT
    def Pack(self, builder):
        if self.branchSubgraphIndices is not None:
            if np is not None and type(self.branchSubgraphIndices) is np.ndarray:
                branchSubgraphIndices = builder.CreateNumpyVector(self.branchSubgraphIndices)
            else:
                StablehloCaseOptionsStartBranchSubgraphIndicesVector(builder, len(self.branchSubgraphIndices))
                for i in reversed(range(len(self.branchSubgraphIndices))):
                    builder.PrependInt32(self.branchSubgraphIndices[i])
                branchSubgraphIndices = builder.EndVector()
        StablehloCaseOptionsStart(builder)
        if self.branchSubgraphIndices is not None:
            StablehloCaseOptionsAddBranchSubgraphIndices(builder, branchSubgraphIndices)
        stablehloCaseOptions = StablehloCaseOptionsEnd(builder)
        return stablehloCaseOptions
