# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StablehloShiftLeftOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StablehloShiftLeftOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStablehloShiftLeftOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StablehloShiftLeftOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # StablehloShiftLeftOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def StablehloShiftLeftOptionsStart(builder):
    builder.StartObject(0)

def Start(builder):
    StablehloShiftLeftOptionsStart(builder)

def StablehloShiftLeftOptionsEnd(builder):
    return builder.EndObject()

def End(builder):
    return StablehloShiftLeftOptionsEnd(builder)


class StablehloShiftLeftOptionsT(object):

    # StablehloShiftLeftOptionsT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        stablehloShiftLeftOptions = StablehloShiftLeftOptions()
        stablehloShiftLeftOptions.Init(buf, pos)
        return cls.InitFromObj(stablehloShiftLeftOptions)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, stablehloShiftLeftOptions):
        x = StablehloShiftLeftOptionsT()
        x._UnPack(stablehloShiftLeftOptions)
        return x

    # StablehloShiftLeftOptionsT
    def _UnPack(self, stablehloShiftLeftOptions):
        if stablehloShiftLeftOptions is None:
            return

    # StablehloShiftLeftOptionsT
    def Pack(self, builder):
        StablehloShiftLeftOptionsStart(builder)
        stablehloShiftLeftOptions = StablehloShiftLeftOptionsEnd(builder)
        return stablehloShiftLeftOptions
